version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/StreamAwesome"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependency"
      
